name: Deploy to Vercel

on:
  push:
    branches:
      - '**'  # Trigger on push to any branch

  pull_request:
    branches:
      - '**'  # Trigger on PR to any branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "Deploying to production..."
            vercel --prod --confirm --token=$VERCEL_TOKEN
          else
            echo "Deploying to preview..."
            vercel --confirm --token=$VERCEL_TOKEN
          fi