name: Lint Supabase SQL

on:
  pull_request:
    paths:
      - 'supabase/functions/**/*.sql'
      - 'supabase/migrations/**/*.sql'

  push:
    branches:
      - main
      - develop
    paths:
      - 'supabase/functions/**/*.sql'
      - 'supabase/migrations/**/*.sql'

jobs:
  lint-sql:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Supabase SQL lint
        env:
          DATABASE_URL: ${{ secrets.SUPABASE_DB_URL }}  
        run: |
          npx supabase db lint --db-url "$DATABASE_URL"
