name: Run Supabase Functions Daily

on:
  schedule:
    - cron: '30 18 * * *'  # Runs daily at 12:00 AM IST (UTC+5:30)
  workflow_dispatch:

jobs:
  call-supabase-functions:
    runs-on: ubuntu-latest
    env:
      SUPABASE_API_KEY: ${{ secrets.SUPABASE_API_KEY }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      SUPABASE_URL: https://eakvpbpzruxtwmcvkltc.supabase.co

    steps:
      - name: Call assign_daily_words
        run: |
          curl -X POST "$SUPABASE_URL/rest/v1/rpc/assign_daily_words" \
          -H "apikey: $SUPABASE_API_KEY" \
          -H "Authorization: Bearer $SUPABASE_SERVICE_ROLE_KEY" \
          -H "Content-Type: application/json" \
          -d '{"run_type":"auto"}'

      - name: Call get_user_word_analytics
        run: |
          curl -X POST "$SUPABASE_URL/rest/v1/rpc/get_user_word_analytics" \
          -H "apikey: $SUPABASE_API_KEY" \
          -H "Authorization: Bearer $SUPABASE_SERVICE_ROLE_KEY" \
          -H "Content-Type: application/json" \
          -d '{"run_type":"auto"}'
